petstagram/accounts/urls.py
from django.urls import path, include

from petstagram.accounts import views

urlpatterns = [
    path('login', views.login, name='login'),
    path('register/', views.register, name='register'),
    path('profile/<int:pk>/', include([
        path('', views.profile_details, name='profile-details'),
        path('edit/', views.profile_edit, name='profile-edit'),
        path('delete', views.profile_delete, name='profile-delete'),
    ]))
]

petstagram/common/urls.py
from django.urls import path

from petstagram.common import views

urlpatterns = [
    path('', views.home_page, name='home'),
    path('like/<int:photo_id>/', views.likes_functionality, name='like'),
    path('share/<int:phpto_id>/', views.share_functionality, name='share'),
]

petstagram/pets/urls.py
from django.urls import path, include

from petstagram.pets import views

urlpatterns = [
    path('add/', views.pet_add_page, name='add-pet'),
    path('<str:username>/pet<slug:pet_slug>/', include([
        path('', views.pet_details_page, name='pet-details'),
        path('edit/', views.pet_edit_page, name='edit-pet'),
        path('delete/', views.pet_delete_page, name='delete-pet'),
    ])),
]

petstagram/photos/urls.py
from django.urls import path, include

from petstagram.photos import views

urlpatterns = [
    path('add/', views.photo_add_page, name='photo-add'),
    path('<int:pk>/', include([
        path('', views.photo_details_page, name='photo-details'),
        path('add/', views.photo_edit_page, name='photo-edit'),
    ])),
]

petstagram/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('petstagram.common.urls')),
    path('accounts/', include('petstagram.accounts.urls')),
    path('pets/', include('petstagram.pets.urls')),
    path('photos/', include('petstagram.photos.urls')),
]

petstagram/accounts/models.py
from django.db import models

# Create your models here.

petstagram/common/models.py
from django.db import models

from petstagram.photos.models import Photo


class Comment(models.Model):
    text = models.TextField(max_length=300,)
    date_time_of_publication = models.DateTimeField(auto_now_add=True, )
    to_photo = models.ForeignKey(to=Photo, on_delete=models.CASCADE, )


class Like(models.Model):
    to_photo = models.ForeignKey(to=Photo, on_delete=models.CASCADE, )

petstagram/pets/models.py
from django.db import models
from django.template.defaultfilters import slugify


class Pet(models.Model):
    name = models.CharField(max_length=30,)
    personal_photo = models.URLField()
    date_of_birth = models.DateField(blank=True, null=True,)
    slug = models.SlugField(null=True, blank=True, unique=True,editable=False,)


    def save(self, *args, **kwargs):
        super().save(*args, **kwargs)

        if not self.slug:  # self.name, self.id -> Rangel Petrov 5 -> slugify -> rangel-petrov-5
            self.slug = slugify(f"{self.name}-{self.id}")

        super().save(*args, **kwargs)


    def __str__(self):
        return  self.name

petstagram/photos/models.py
from django.core.validators import MinLengthValidator
from django.db import models

from petstagram.pets.models import Pet
from petstagram.photos.validators import FileSizeValidator


class Photo(models.Model):
    photo = models.ImageField(upload_to='mediafiles', validators=[FileSizeValidator(5),])
    description = models.TextField(max_length=300, validators=(MinLengthValidator(10), ), blank=True, null=True,)
    location = models.CharField(max_length=30, blank=True, null=True,)
    tagged_pets = models.ManyToManyField(to=Pet, blank=True,)
    date_of_publication = models.DateField(auto_now_add=True)

petstagram/accounts/views.py
from django.shortcuts import render


# Create your views here.
def register(request):
    return render(request, 'accounts/register-page.html')


def login(request):
    return render(request, 'accounts/login-page.html')


def profile_details(request, pk: int):
    return render(request, 'accounts/profile-details-page.html')


def profile_edit(request, pk: int):
    return render(request, 'accounts/profile-edit-page.html')


def profile_delete(request, pk: int):
    return render(request, 'accounts/profile-delete-page.html')

petstagram/common/views.py
from django.shortcuts import render, redirect, resolve_url
from pyperclip import copy

from petstagram.photos.models import Photo
from petstagram.common.models import Like
# Create your views here.
def home_page(request):

    all_photos = Photo.objects.all()

    context = {
        'all_photos': all_photos
    }

    return render(request, 'common/home-page.html', context)
def likes_functionality(request, photo_id: int):
    liked_object = Like.objects.filter(
        to_photo_id=photo_id
    ).first()

    if liked_object:
        liked_object.delete()
    else:
        like = Like(to_photo_id=photo_id)
        like.save()

    return redirect(request.META.get('HTTP_REFERER') + f'#{photo_id}')


def share_functionality(request, photo_id: int):
    copy(request.META.get('HTTP+HOST') + resolve_url('photo-details', photo_id))
    #HTTP_HOST = http://127.0.0.1/ + photo/<int:pk>/ => http://127.0.0.1/photos/<int:pk>/

    return redirect(request.META.get('HTTP_REFERER') + f'#{photo_id}')

petstagram/pets/views.py
from django.shortcuts import render

from petstagram.pets.models import Pet


# Create your views here.
def pet_add_page(request):
    return render(request, 'pets/pet-add-page.html')


def pet_edit_page(request, username: str, pet_slug: str):
    return render(request, 'pets/pet-edit-page.html')


def pet_delete_page(request, username: str, pet_slug: str):
    return render(request, 'pets/pet-delete-page.html')


def pet_details_page(request, username: str, pet_slug: str):
    pet = Pet.objects.get(slug=pet_slug)
    all_photos = pet.photo_set.all()

    context = {
        'pet': pet,
        'all_photos': all_photos,
    }
    return render(request, 'pets/pet-details-page.html', context)

petstagram/photos/views.py
from django.shortcuts import render


# Create your views here.

def photo_add_page(request):
    return render(request, 'photos/photo-add-page.html')


def photo_edit_page(request, pk: int):
    return render(request, 'photos/photo-edit-page.html')


def photo_details_page(request, pk: int):
    return render(request, 'photos/photo-details-page.html')

templates/accounts/login-page.html
{% extends 'common/base.html' %}

{% block content %}
    <!-- Start Login Section-->
    <div class="login-register-div">
        <div class="login-register-box">
            <h1>Petstagram</h1>

            <!-- Start Login Form-->
            <form action="#">
                <p>
                    <label for="id_username">Username:</label>
                    <input type="text" placeholder="Username">
                </p>
                <p>
                    <label for="id_password">Password:</label>
                    <input type="password" placeholder="Password">
                </p>

                <!-- Login Button-->
                <button type="submit">Log in</button>
            </form>
            <!-- End Login Form -->

        </div>
        <div class="second-option">

            <!-- Link to Register Page-->
            <p>Don't have an account? <a href="#">Register</a></p>
        </div>
    </div>

{% endblock %}

templates/accounts/profile-delete-page.html
{% extends 'common/base.html' %}

{% block content %}
    <!-- Start Delete Profile Section -->
        <div class="delete-profile">
            <h1>
                Are you sure you want to delete your profile?
            </h1>
            <div class="sure-buttons">
                <!-- Yes (Delete Profile) Button -->
                <button>Yes</button>
                <!-- Go Back Button -->
                <a class="edit-btn" href="javascript:history.back()">Go Back</a>
            </div>
            <img src="/static/images/are_you_sure_cat.gif" alt="are you sure cat git">
        </div>
    <!-- End Delete Profile Section -->
{% endblock %}

templates/accounts/profile-details-page.html
{% extends 'common/base.html' %}

{% block content %}
      <!-- Start Profile Details Section -->
      <div class="profile">
        <!-- Start Profile Personal Data Section -->
        <div class="profile-data">
          <div class="profile_img">
            <div class="image">
              <!-- Profile Image -->
              <img src="/static/images/person.png" alt="img8" />
            </div>
          </div>
          <div class="personal">
            <div class="edit">
              <!-- User Username -->
              <p>d_kalaydzhiev</p>

              <!-- IF the viewer is the owner of the profile -->
              <!-- Link to Edit Profile Page -->
              <a href="#">
                <img
                  class="edit-img"
                  src="/static/images/edit-pen-icon-6.jpg"
                  alt="edit button"
                />
              </a>

              <!-- Link to Delete Profile Page -->
              <a href="">
                <img
                  class="bin-img"
                  src="/static/images/icon-remove-22.jpg"
                  alt="bin button"
                />
              </a>
              <!-- End IF the viewer is the owner of the profile -->
            </div>
            <div class="data">
              <!-- Total Number of Photos by the User -->
              <span>4</span>
              <p>photos</p>

              <!-- Total Number of Pets owned by the User -->
              <span>7</span>
              <p>pets</p>

              <!-- Total Number of Likes for the User -->
              <span>436</span>
              <p>likes</p>
            </div>
            <!-- User First and Last Name IF Added -->
            <h3 class="names">Diyan Kalaydziev</h3>

            <!-- User Email Address -->
            <p class="email">d.denov@gmail.com</p>

            <!-- User Gender IF Added -->
            <p class="gender">Male</p>
          </div>
        </div>
        <!-- End Profile Personal Data Section -->

        <!-- Start Pets Data Section -->
        <div class="pets">
          <div class="statuses">
            <!-- Start 1st Pet Details Page -->
            <!-- Link to First Pet Details Page -->
            <a href="#">
              <div class="head-pet">
                <div class="status">
                  <div class="image">
                    <!-- Pet Image -->
                    <img
                      src="https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTgoIHq82qLYnvomfz5ZkW5CLQ8VNxCyI-hUw&usqp=CAU"
                      alt="pet img"
                    />
                  </div>
                </div>
                <!-- Pet Name -->
                <p>Sasho</p>
              </div>
            </a>
            <!-- End 1st Pet Details Page -->

            <!-- Start 2nd Pet Details Page -->
            <!-- Link to Second Pet Details Page -->
            <a href="#">
              <div class="head-pet">
                <div class="status">
                  <div class="image">
                    <!-- Pet Image -->
                    <img
                      src="https://cdn.pixabay.com/photo/2016/12/13/05/15/puppy-1903313__340.jpg"
                      alt="pet img"
                    />
                  </div>
                </div>
                <!-- Pet Name -->
                <p>Todi</p>
              </div>
            </a>
            <!-- End 2nd Pet Details Page -->

            <!-- Start 3rd Pet Details Page -->
            <!-- Link to Pet Details Page -->
            <a href="#">
              <div class="head-pet">
                <div class="status">
                  <div class="image">
                    <img
                      src="https://images.unsplash.com/photo-1611003228941-98852ba62227?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxzZWFyY2h8MXx8YmFieSUyMGRvZ3xlbnwwfHwwfHw%3D&w=1000&q=80"
                      alt="pet img"
                    />
                  </div>
                </div>
                <p>Mihail</p>
              </div>
            </a>
            <!-- End 3rd Pet Details Page -->

            <!-- Start 4th Pet Details Page -->
            <!-- Link to Pet Details Page -->
            <a href="#">
              <div class="head-pet">
                <div class="status">
                  <div class="image">
                    <img
                      src="https://upload.wikimedia.org/wikipedia/commons/thumb/3/3a/Cat03.jpg/1200px-Cat03.jpg"
                      alt="pet img"
                    />
                  </div>
                </div>
                <p>Petar</p>
              </div>
            </a>
            <!-- End 4th Pet Details Page -->

            <!-- Start 5th Pet Details Page -->
            <!-- Link to Pet Details Page -->
            <a href="#">
              <div class="head-pet">
                <div class="status">
                  <div class="image">
                    <img
                      src="https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQdKYe00NaD5SQjIMvXYPssq0r1dXJggL3ZIg&usqp=CAU"
                      alt="pet img"
                    />
                  </div>
                </div>
                <p>Stamat</p>
              </div>
            </a>
            <!-- End 5th Pet Details Page -->

            <!-- Start 6th Pet Details Page -->
            <!-- Link to Pet Details Page -->
            <a href="#">
              <div class="head-pet">
                <div class="status">
                  <div class="image">
                    <img
                      src="https://cf.ltkcdn.net/small-pets/images/orig/278587-1600x1066-goldfish-swimming-in-fish-tank.jpg"
                      alt="pet img"
                    />
                  </div>
                </div>
                <p>Toni</p>
              </div>
            </a>
            <!-- End 6th Pet Details Page -->

            <!-- Start 7th Pet Details Page -->
            <!-- Link to Pet Details Page -->
            <a href="#">
              <div class="head-pet">
                <div class="status">
                  <div class="image">
                    <img
                      src="https://i.pinimg.com/736x/01/6f/72/016f72c5812e1b8f71bdbf19d8c7558b.jpg"
                      alt="pet img"
                    />
                  </div>
                </div>
                <p>Daisy</p>
              </div>
            </a>
            <!-- End 7th Pet Details Page -->
          </div>
        </div>
        <!-- End Pets Data Section -->

        <!-- Start Last Uploaded Photos Section -->
        <div class="pet-photos">
          <!-- Link to Last Uploaded Pet Photo -->
          <a href="#">
            <!-- Pet Photo -->
            <img
              src="https://i.natgeofe.com/n/de94c416-6d23-45f5-9708-e8d56289268e/naturepl_01132178.jpg?w=636&h=631"
              alt="pet img"
            />
          </a>

          <!-- Link to Uploaded Pet Photo -->
          <a href="#">
            <!-- Pet Photo -->
            <img
              src="https://cf.ltkcdn.net/small-pets/images/orig/278587-1600x1066-goldfish-swimming-in-fish-tank.jpg"
              alt="pet img"
            />
          </a>

          <!-- Link to Uploaded Pet Photo -->
          <a href="#">
            <!-- Pet Photo -->
            <img
              src="https://thumbs.dreamstime.com/b/small-golden-retriever-puppy-6482030.jpg"
              alt="pet img"
            />
          </a>

          <!-- Link to  Uploaded Pet Photo -->
          <a href="#">
            <!-- Pet Photo -->
            <img
              src="https://i.pinimg.com/originals/4e/55/83/4e5583748bc4000805df50e4ebcafffc.png"
              alt="pet img"
            />
          </a>
        </div>
        <!-- End Last Uploaded Photos Section -->

        <!-- IF NO Posts Show No Post Image -->

        <img
          class="no-posts"
          src="/static/images/no_posts.png"
          alt="no posts"
        />
      </div>
        
{% endblock %}        

templates/accounts/profile-edit-page.html
{% extends 'common/base.html' %}

{% block content %}
    <!-- Start Edit Profile Section -->
    <div class="edit-delete">
        <h2>Edit Profile</h2>
        <!-- Start Edit Profile From -->
        <form action="">
            <div class="label-input">
                <label for="first name">First name: </label>
                <input type="text" placeholder="First name" value="Diyan">
            </div>
            <br>
            <div class="label-input">
                <label for="last name">Last name: </label>
                <input type="text" placeholder="Last name" value="Kalayadzhiev">
            </div>
            <br>
            <div class="label-input">
                <label for="username">Username: </label>
                <input type="text" placeholder="Username" value="k_dido">
            </div>
            <br>
            <div class="label-input">
                <label for="email">Email: </label>
                <input type="email" placeholder="Email" value="d.denov@gmail.com">
            </div>
            <br>
            <div class="label-input">
                <label for="image">Image: </label>
                <input type="text" placeholder="Link to to profile picture"
                       value="https://i.natgeofe.com/n/de94c416-6d23-45f5-9708-e8d56289268e/naturepl_01132178.jpg?w=636&h=631">
            </div>
            <br>

            <div class="label-input">
                <label for="image">Gender: </label>
                <div class="list-choice">
                    <div class="list-choice-title">Gender</div>
                    <div class="list-choice-objects">
                        <label>
                            <input type="radio" name="gender"/> <span>Male</span>
                        </label>
                        <label>
                            <input type="radio" name="gender"/> <span>Female</span>
                        </label>
                        <label>
                            <input type="radio" name="gender"/> <span>Do not show</span>
                        </label>
                    </div>
                </div>
            </div>

            <!-- Edit Profile Button -->
            <button class="edit-btn" type="submit">Edit</button>
        </form>
        <!-- End Edit Profile Form -->

    </div>
{% endblock  %}

templates/accounts/register-page.html
{% extends 'common/base.html' %}

{% block content %}

    <div class="login-register-div">
        <div class="login-register-box">
            <h1>Petstagram</h1>

            <!-- Start Register Form -->
            <form action="">
                <input type="text" placeholder="Username">

                <input type="email" placeholder="Email">

                <input type="password" placeholder="Password">

                <input type="password" placeholder="Repeat Password">

                <!-- Register Button -->
                <button type="submit">Register</button>
            </form>
            <!-- End Register Form -->

        </div>
        <div class="second-option">

            <!-- Link to Login Page -->
            <p>Have an account? <a href="#">Log in</a></p>
        </div>
    </div>
{% endblock %}

templates/common/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<!-- Starts Head Section -->
<head>
    <link rel="stylesheet" href="{% static 'css/styles.css' %}">
    <link rel="icon" type="image/x-icon" href="{% static 'images/free-30-instagram-stories-icons23_122570.png' %}">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.1/css/all.min.css"
          integrity="sha512-DTOQO9RWCH3ppGqcWaEA1BIZOC6xxalwEsw9c2QQeAIftl+Vegovlnee1c9QX4TctnWMn13TZye+giMm8e2LwA=="
          crossorigin="anonymous" referrerpolicy="no-referrer"/>
    <title>Petstagram</title>
</head>

<body>

<header>
    {% include 'common/nav.html' %}
</header>

<main>

    {% block content %}
    {% endblock %}

</main>


<div class="footer">
       <span class="footer-section">
          © 2024 SOFTUNI WORKSHOP FOR PYTHON WEB MODULE
       </span>
</div>

templates/common/home-page.html
{% extends 'common/base.html' %}
{% load static %}

{% block content %}

    <div class="container">
        <div class="col-9">

            <!-- Start Searchbar Form -->
            <form class="searchbar" method="post">
                <input type="text" placeholder="Search by pet name...">
                <button>
                    <img src="{% static '/images/search.png' %}" height="18" alt="img2">
                </button>
            </form>
            
            {% for photo in all_photos %}
                {% include 'common/pet-posts.html' %}
            {% endfor %}
        
        </div>
    </div>
{% endblock %}

templates/common/nav.html
{% load static %}


<nav class="navbar">
        <div class="container">
            <div class="logo">
                <!-- Link to Home Page -->
                <a href="#">
                    <img width="50px" src="{% static 'images/free-30-instagram-stories-icons23_122570.png' %}"
                         alt="img1">
                </a>

                <!-- Link to Home Page -->
                <a class="home" href="{% url 'home' %}">
                    <i>Petstagram</i>
                </a>
            </div>

            <div class="nav-links">
                <ul class="nav-group">
                    <li class="nav-item">

                        <!-- Link to Add Pet Page -->
                        <a href="{% url 'add-pet' %}">
                            <i>Add Pet</i>
                        </a>
                    </li>
                    <li class="nav-item">

                        <!-- Link to Add Photo Page -->
                        <a href="{% url 'photo-add' %}">
                            <i>Add Photo</i>
                        </a>
                    </li>
                    <li class="nav-item">

                        <!-- Link to Login Page -->
                        <a href="{% url 'login' %}">
                            <i>Login</i>
                        </a>
                    </li>
                    <li class="nav-item">

                        <!-- Link to Register Page -->
                        <a href="{% url 'register' %}">
                            <i>Register</i>
                        </a>
                    </li>
                    <li class="nav-item">

                        <!-- Link to Profile Page -->
                        <a href="#">
                            <i>Profile</i>
                        </a>
                    </li>
                    <li class="nav-item">
                        <a href="#">
                            <i>Logout</i>
                        </a>
                    </li>
                </ul>
            </div>
        </div>
    </nav>

templates/common/pet-posts.html
<div class="card">
    <div class="top">
        <!-- User Details and image location -->
        <div class="userDetails">
            <a href="profile details">
                <div class="profilepic">
                    <div class="profile_img">
                        <div class="image">
                            <img src="/static/images/person.png" alt="img8">
                        </div>
                    </div>
                </div>
            </a>
            <h3>
                <a href="profile details">
                    <!-- if user has first name and last name -->
                    Diyan Kalaydzhiev
                    <!-- else -->
                    <!-- user username -->
                </a>
                <br>
                <!-- if the photo has location -->
                {% if photo.location %}
                    <span>{{ photo.location }}</span>
                {% endif %}
            </h3>
        </div>
        <!--  -->
    </div>
    <!-- Post image -->
    <div class="imgBx" id="{{ photo.pk }}">
        <img src="{{ photo.photo.url }}" alt="post" class="cover">
    </div>
    <!-- -->

    <div class="bottom">
        <!-- like and share buttons -->
        <div class="actionBtns">
            <div class="left">
                    <span class="heart">
                        <a href="{% url 'like' photo.pk %}">
                            {% if photo.like_set.all %}
                                <i class="fa-solid fa-heart" style="color: #ed4040;"></i>
                            {% else %}
                                <i class="fa-regular fa-heart"></i>
                            {% endif %}
                        </a>
                    </span>
                <a href="{% url 'share' photo.pk %}">
                    <i class="fa-solid fa-share"></i>
                </a>
            </div>
        </div>
        <a href="#">
            <p class="likes">{{ photo.like_set.count }}</p>
        </a>
    
        {% for pet in photo.tagged_pets.all %}
        
            <a href="{% url 'pet-details' "username" pet.slug %}">
               <p class="message">
                   <b>{{ pet.name }}</b>
               </p>
            </a>
        {% endfor %}
    
        <a href="{% url 'photo-details' photo.pk %}">
            <h4 class="details">See details</h4>
        </a>

        <h5 class="postTime">{{ photo.date_of_publication }}</h5>

        <!-- add comments section -->
        <div class="addComments">

            <form method="post" action="add comment">
                <label for="id_body">Body:</label>
                <textarea name="body" cols="40" rows="10" placeholder="Add comment..." maxlength="300"
                          required="" id="id_body"></textarea>
                <button type="submit">Post</button>
            </form>
        </div>
        <!--  -->
    </div>
</div>
<!-- End  First Pet Photo Post -->
<div class="card">
    <div class="top">
        <!-- User Details and image location -->
        <div class="userDetails">
            <a href="profile details">
                <div class="profilepic">
                    <div class="profile_img">
                        <div class="image">
                            <img src="/static/images/person.png" alt="img8">
                        </div>
                    </div>
                </div>
            </a>
            <h3>
                <a href="profile details">
                    <!-- if user has first name and last name -->
                    Diyan Kalaydzhiev
                    <!-- else -->
                    <!-- user username -->
                </a>
                <br>
                <!-- if the photo has location -->
                <span>Bansko, Bulgaria</span>
            </h3>
        </div>
        <!--  -->
    </div>
    <!-- Post image -->
    <div class="imgBx" id="place the id of the photo here">
        <img src="https:///static.scientificamerican.com/sciam/cache/file/766BFBD4-F8A1-4B7D-8416A370010B5A88_source.jpg"
             alt="post" class="cover">
    </div>
    <!-- -->

    <div class="bottom">
        <!-- like and share buttons -->
        <div class="actionBtns">
            <div class="left">
                    <span class="heart">
                        <a href="#">
                            <!-- if user has liked the photo -->
                            <i class="fa-solid fa-heart" style="color: #ed4040;"></i>
                            <!-- else -->
                            <i class="fa-regular fa-heart"></i>
                        </a>
                    </span>
                <a href="share">
                    <i class="fa-solid fa-share"></i>
                </a>
            </div>
        </div>
        <!-- -->

        <a href="#">
            <p class="likes">203 likes</p>
        </a>

        <!-- tagged pets -->
        <a href="pet profile">
            <p class="message">
                <b>Sasho</b>
            </p>
        </a>
        <a href="pet profile">
            <p class="message">
                <b>Some other fish</b>
            </p>
        </a>
        <!--  -->

        <a href="post details">
            <h4 class="details">See details</h4>
        </a>

        <h5 class="postTime">19/09/2022</h5>

        <!-- add comments section -->
        <div class="addComments">

            <form method="post" action="add comment">
                <label for="id_body">Body:</label>
                <textarea name="body" cols="40" rows="10" placeholder="Add comment..." maxlength="300"
                          required="" id="id_body"></textarea>
                <button type="submit">Post</button>
            </form>
        </div>
        <!--  -->
    </div>
</div>

templates/photos/photo-add-page.html
{% extends 'common/base.html' %}

{% block content %} 

    <div class="edit-delete edit-photo">
        <h2>Add photo</h2>
        <!-- Start Add Photo Form -->
        <form action="" enctype="multipart/form-data">
            <p>
                <label for="id_photo_file">Photo file:</label>
                <input type="file">
            </p>

            <p>
                <label for="id_description">Description:</label>
                <input type="text">
            </p>

            <p>
                <label for="id_description">Location:</label>
                <input type="text" name="photo_shooting_location" maxlength="50" id="id_photo_shooting_location">
            </p>

            <p>
                <label for="pets">Tag Pets:</label>

                <select name="pets" id="id_tagged_pets" multiple>
                    <option>Sasho</option>
                    <option>Perry</option>
                    <option>Bucky</option>
                    <option>Steve</option>
                </select>
            </p>
            <!-- Add Photo Button -->
            <button class="add-btn" type="submit">Add Photo</button>
        </form>
        <!-- End Add Photo Form -->
    </div>
    <!-- End Add Photo Section -->
{% endblock %}

templates/photos/photo-edit-page.html
{% extends 'common/base.html' %}

{% block content %}

    <!-- Starts Edit Photo Section -->
    <div class="edit-delete edit-photo">
        <h2>Edit photo</h2>

        <!-- Starts Edit Photo Form -->
        <form action="">

            <p>
                <label for="id_description">Description:</label>
                <input type="text" value="Sasho is an Axolotl">
            </p>

            <p>
                <label for="id_description">Location:</label>
                <input type="text" name="photo_shooting_location" maxlength="50" id="id_photo_shooting_location"
                       value="Bansko, Bulgaria">
            </p>

            <p>
                <label for="pets">Tag Pets:</label>

                <select name="pets" id="id_tagged_pets" multiple>
                    <option selected>Sasho</option>
                    <option>Perry</option>
                    <option>Bucky</option>
                    <option>Steve</option>
                </select>
            </p>

            <!-- Edit Photo Button -->
            <button class="edit-btn" type="submit">Edit Photo</button>
        </form>
        <!-- End Edit Photo Form -->

    </div>
    <!-- End Edit Photo Section -->

{% endblock %}